#
# This file is part of Saft.
#
# (c) Konrad Abicht <hi@inspirito.de>
# (c) Natanael Arndt <arndt@informatik.uni-leipzig.de>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#

erfurtConfig: &erfurtConfig
    cache:
        backend:
            file:
                cache_dir: "" # will be set later on
            type: "file"
        frontend:
            cache_id_prefix: "saft_"
            enable: true
            lifetime: 0
        query: # query cache related
            enable: 1
            type: "database"
    store:
        backend: "zenddb" # change that to virtuoso to enable Virtuoso backend
        zenddb:
            dbname: "saft"
            username: "root"
            password: "Pass123"
            dbtype: "mysql"
            host: "sqldb"
        virtuoso:
            dsn: "VOS"
            username: "dba"
            password: "dba"
